# Generated by Django 3.1.6 on 2021-02-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='bio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
