# Generated by Django 3.1.6 on 2021-02-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='inst_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts', to='university.institute'),
        ),
    ]
