# Generated by Django 3.1.6 on 2021-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20210423_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='notes',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
