# Generated by Django 3.1.6 on 2021-03-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20210302_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='premium',
            field=models.BooleanField(default=True),
        ),
    ]
