# Generated by Django 3.1.6 on 2021-03-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_lecture_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='lecture_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.course'),
            preserve_default=False,
        ),
    ]
